apiVersion: v1
kind: ServiceAccount
metadata: {name: queueless, namespace: queueless}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: queueless-read-config, namespace: queueless}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: queueless-read-config, namespace: queueless}
subjects:
- kind: ServiceAccount
  name: queueless
  namespace: queueless
roleRef: {kind: Role, name: queueless-read-config, apiGroup: rbac.authorization.k8s.io}
