apiVersion: v1
kind: Secret
metadata:
  name: queueless-secret
  namespace: sagarmauroz-dev
type: Opaque
stringData:
  POSTGRES_DB: "queueless"
  POSTGRES_USER: "queueless"
  POSTGRES_PASSWORD: "QueueLessDB2026!"
  DATABASE_URL: "postgresql+psycopg://queueless:QueueLessDB2026%21@postgres:5432/queueless"