apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: queueless
  namespace: sagarmauroz
  labels:
    app: queueless
spec:
  selector:
    matchLabels:
      app: queueless

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s