apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: queueless-serverless
  namespace: sagarmauroz-dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: ghcr.io/sagarmauroz-hash/qseva-serverless:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
